### ISSUE TITLE
使用MCL启动词库插件,缓存图片会报错

### ISSUE THREAD

**Issue by realseek** [BillYang2016/entrylib#12]
``2021-08-11 17:08:12 V/Bot.1060373949: [bot内部测试(640866550)] (1536266519) -> [mirai:image:{1D87C261-6BB9-75D3-4DF5-39A3DFFE3BB0}.jpg]
2021-08-11 17:08:12 W/stderr: java.io.FileNotFoundException: data\EntryLib\images\{1D87C261-6BB9-75D3-4DF5-39A3DFFE3BB0}.jpg (系统找不到指定的路径。)
2021-08-11 17:08:12 W/stderr:   at java.base/java.io.FileOutputStream.open0(Native Method)
2021-08-11 17:08:12 W/stderr:   at java.base/java.io.FileOutputStream.open(FileOutputStream.java:298)
2021-08-11 17:08:12 W/stderr:   at java.base/java.io.FileOutputStream.<init>(FileOutputStream.java:237)
2021-08-11 17:08:12 W/stderr:   at java.base/java.io.FileOutputStream.<init>(FileOutputStream.java:126)
2021-08-11 17:08:12 W/stderr:   at com.billyang.entrylib.MiraiCodeParser.ImageParser.downloadImage(ImageParser.java:59)
2021-08-11 17:08:12 W/stderr:   at com.billyang.entrylib.MiraiCodeParser.ImageParser.Image2PlainText(ImageParser.java:108)
2021-08-11 17:08:12 W/stderr:   at com.billyang.entrylib.MiraiCodeParser.CodeParser.Encode(CodeParser.java:66)
2021-08-11 17:08:12 W/stderr:   at com.billyang.entrylib.EntryLib.lambda$onEnable$0(EntryLib.java:525)
2021-08-11 17:08:12 W/stderr:   at net.mamoe.mirai.event.EventChannel$subscribeAlways$2$1.invoke(EventChannel.kt:512)
2021-08-11 17:08:12 W/stderr:   at net.mamoe.mirai.event.EventChannel$subscribeAlways$2$1.invoke(EventChannel.kt:512)
2021-08-11 17:08:12 W/stderr:   at kotlinx.coroutines.InterruptibleKt.runInterruptibleInExpectedContext(Interruptible.kt:46)
2021-08-11 17:08:12 W/stderr:   at kotlinx.coroutines.InterruptibleKt.access$runInterruptibleInExpectedContext(Interruptible.kt:1)
2021-08-11 17:08:12 W/stderr:   at kotlinx.coroutines.InterruptibleKt$runInterruptible$2.invokeSuspend(Interruptible.kt:38)
2021-08-11 17:08:12 W/stderr:   at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
2021-08-11 17:08:12 W/stderr:   at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
2021-08-11 17:08:12 W/stderr:   at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:571)
2021-08-11 17:08:12 W/stderr:   at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:750)
2021-08-11 17:08:12 W/stderr:   at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:678)
2021-08-11 17:08:12 W/stderr:   at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:665)``

**Comment by realseek** [comment]
> 需要更多问题相关信息：
> 
> 1. `{1D87C261-6BB9-75D3-4DF5-39A3DFFE3BB0}.jpg`图片文件是否存在？
> 2. 图片文件是否符合发送的图片？
> 3. 多次尝试是否仍然出现问题？

1.在使用群内的一键包时 图片可以正常保存 且存在
2.符合
3.多次重启仍有此问题且只在[MCL](https://github.com/iTXTech/mirai-console-loader) 内发生此错误

**Comment by realseek** [comment]
> > 1.在使用群内的一键包时 图片可以正常保存 且存在
> > 2.符合
> > 3.多次重启仍有此问题且只在[MCL](https://github.com/iTXTech/mirai-console-loader) 内发生此错误
> 
> 是所有图片都会发生这个错误吗

是的

**Comment by BillYang2016** [comment]
问题原因：mcl的java目录不在mirai中，导致相对路径错误

**Comment by BillYang2016** [comment]
可以提供一下 jre/jdk 版本吗，如果方便的话麻烦添加一下 README 中的 QQ 群

**Comment by BillYang2016** [comment]
目前的调查情况：
1. java8 与 java11 的文档描述完全相同，因此可能不是由java版本引起的问题
2. 抛出 FileNotFoundException 后，插件依然正常执行了所有工作（第一层递归错误信息是在 Native Method 中汇报的，很难查错）
3. 错误信息中的路径疑似是相对路径，是否是由相对路径引起的问题（但 File 类并没有相同错误汇报，为什么 File 类与 FileOutputStream 类表现不同）

**Comment by BillYang2016** [comment]
> 目前的调查情况：
> 
> 1. java8 与 java11 的文档描述完全相同，因此可能不是由java版本引起的问题
> 2. 抛出 FileNotFoundException 后，插件依然正常执行了所有工作（第一层递归错误信息是在 Native Method 中汇报的，很难查错）
> 3. 错误信息中的路径疑似是相对路径，是否是由相对路径引起的问题（但 File 类并没有相同错误汇报，为什么 File 类与 FileOutputStream 类表现不同）

根据当事人反馈出现了描述理解错误，第二条已解决，1.1.0 版本并没有正常执行所有工作（没有正常缓存图片）
剩下的待解决问题：（实在想不通）
**为何 MCL 环境对 FileOutputStream 类提供相对路径会出现错误，而 File 类提供相对路径则正常执行**

**Comment by Ag-elf** [comment]
> > 目前的调查情况：
> > 
> > 1. java8 与 java11 的文档描述完全相同，因此可能不是由java版本引起的问题
> > 2. 抛出 FileNotFoundException 后，插件依然正常执行了所有工作（第一层递归错误信息是在 Native Method 中汇报的，很难查错）
> > 3. 错误信息中的路径疑似是相对路径，是否是由相对路径引起的问题（但 File 类并没有相同错误汇报，为什么 File 类与 FileOutputStream 类表现不同）
> 
> 根据当事人反馈出现了描述理解错误，第二条已解决，1.1.0 版本并没有正常执行所有工作（没有正常缓存图片）
> 剩下的待解决问题：（实在想不通）
> **为何 MCL 环境对 FileOutputStream 类提供相对路径会出现错误，而 File 类提供相对路径则正常执行**

同样使用的是MCL环境，但是图片缓存是正常的。`data/EntryLib/images` 下有对应图片的缓存，行为正常。
猜测是否是路径的处理方式在版本迭代时发生了改变？
插件版本 1.0.3，MCL 1.0.5，mirai-core 2.7-M2

**Comment by realseek** [comment]
> > > 目前的调查情况：
> > > 
> > > 1. java8 与 java11 的文档描述完全相同，因此可能不是由java版本引起的问题
> > > 2. 抛出 FileNotFoundException 后，插件依然正常执行了所有工作（第一层递归错误信息是在 Native Method 中汇报的，很难查错）
> > > 3. 错误信息中的路径疑似是相对路径，是否是由相对路径引起的问题（但 File 类并没有相同错误汇报，为什么 File 类与 FileOutputStream 类表现不同）
> > 
> > 
> > 根据当事人反馈出现了描述理解错误，第二条已解决，1.1.0 版本并没有正常执行所有工作（没有正常缓存图片）
> > 剩下的待解决问题：（实在想不通）
> > **为何 MCL 环境对 FileOutputStream 类提供相对路径会出现错误，而 File 类提供相对路径则正常执行**
> 
> 同样使用的是MCL环境，但是图片缓存是正常的。`data/EntryLib/images` 下有对应图片的缓存，行为正常。
> 插件版本 1.0.3（1.1.0也测试过，没有出现报错），MCL 1.0.5，mirai-core 2.7-M2

我的MCL版本是1.2.2 mirai-core 2.7-M2 插件版本则是升级到1.1.1才可正常使用
