### ISSUE TITLE
[BUG]整理数据库时出错

### ISSUE THREAD

**Issue by SnowMoonSS** [BillYang2016/entrylib#22]
**描述问题 Describe the bug**
```
2022-02-08 13:58:11 I/EntryLib: 开始整理数据库123456789.db
2022-02-08 13:58:11 E/EntryLib: 无法创建新表TABLE_24，五秒后重试！（1/5）
2022-02-08 13:58:11 W/stderr: org.sqlite.SQLiteException: [SQLITE_ERROR] SQL error or missing database (table TABLE_23 already exists)
2022-02-08 13:58:11 W/stderr:   at org.sqlite.core.DB.newSQLException(DB.java:1012)
2022-02-08 13:58:11 W/stderr:   at org.sqlite.core.DB.newSQLException(DB.java:1024)
2022-02-08 13:58:11 W/stderr:   at org.sqlite.core.DB.throwex(DB.java:989)
2022-02-08 13:58:11 W/stderr:   at org.sqlite.core.NativeDB._exec_utf8(Native Method)
2022-02-08 13:58:11 W/stderr:   at org.sqlite.core.NativeDB._exec(NativeDB.java:94)
2022-02-08 13:58:11 W/stderr:   at org.sqlite.jdbc3.JDBC3Statement.executeUpdate(JDBC3Statement.java:102)
2022-02-08 13:58:11 W/stderr:   at com.billyang.entrylib.Database.DatabaseAutoArranger.rearrange(DatabaseAutoArranger.java:293)
2022-02-08 13:58:11 W/stderr:   at com.billyang.entrylib.Database.DatabaseAutoArranger.run(DatabaseAutoArranger.java:490)
2022-02-08 13:58:11 W/stderr:   at java.base/java.util.TimerThread.mainLoop(Timer.java:556)
2022-02-08 13:58:11 W/stderr:   at java.base/java.util.TimerThread.run(Timer.java:506)
2022-02-08 13:58:16 E/EntryLib: 无法创建新表TABLE_24，五秒后重试！（2/5）
2022-02-08 13:58:16 W/stderr: org.sqlite.SQLiteException: [SQLITE_ERROR] SQL error or missing database (table TABLE_23 already exists)
2022-02-08 13:58:16 W/stderr:   at org.sqlite.core.DB.newSQLException(DB.java:1012)
2022-02-08 13:58:16 W/stderr:   at org.sqlite.core.DB.newSQLException(DB.java:1024)
2022-02-08 13:58:16 W/stderr:   at org.sqlite.core.DB.throwex(DB.java:989)
2022-02-08 13:58:16 W/stderr:   at org.sqlite.core.NativeDB._exec_utf8(Native Method)
2022-02-08 13:58:16 W/stderr:   at org.sqlite.core.NativeDB._exec(NativeDB.java:94)
2022-02-08 13:58:16 W/stderr:   at org.sqlite.jdbc3.JDBC3Statement.executeUpdate(JDBC3Statement.java:102)
2022-02-08 13:58:16 W/stderr:   at com.billyang.entrylib.Database.DatabaseAutoArranger.rearrange(DatabaseAutoArranger.java:293)
2022-02-08 13:58:16 W/stderr:   at com.billyang.entrylib.Database.DatabaseAutoArranger.run(DatabaseAutoArranger.java:490)
2022-02-08 13:58:16 W/stderr:   at java.base/java.util.TimerThread.mainLoop(Timer.java:556)
2022-02-08 13:58:16 W/stderr:   at java.base/java.util.TimerThread.run(Timer.java:506)
2022-02-08 13:58:21 E/EntryLib: 无法创建新表TABLE_24，五秒后重试！（3/5）
2022-02-08 13:58:21 W/stderr: org.sqlite.SQLiteException: [SQLITE_ERROR] SQL error or missing database (table TABLE_23 already exists)
2022-02-08 13:58:21 W/stderr:   at org.sqlite.core.DB.newSQLException(DB.java:1012)
2022-02-08 13:58:21 W/stderr:   at org.sqlite.core.DB.newSQLException(DB.java:1024)
2022-02-08 13:58:21 W/stderr:   at org.sqlite.core.DB.throwex(DB.java:989)
2022-02-08 13:58:21 W/stderr:   at org.sqlite.core.NativeDB._exec_utf8(Native Method)
2022-02-08 13:58:21 W/stderr:   at org.sqlite.core.NativeDB._exec(NativeDB.java:94)
2022-02-08 13:58:21 W/stderr:   at org.sqlite.jdbc3.JDBC3Statement.executeUpdate(JDBC3Statement.java:102)
2022-02-08 13:58:21 W/stderr:   at com.billyang.entrylib.Database.DatabaseAutoArranger.rearrange(DatabaseAutoArranger.java:293)
2022-02-08 13:58:21 W/stderr:   at com.billyang.entrylib.Database.DatabaseAutoArranger.run(DatabaseAutoArranger.java:490)
2022-02-08 13:58:21 W/stderr:   at java.base/java.util.TimerThread.mainLoop(Timer.java:556)
2022-02-08 13:58:21 W/stderr:   at java.base/java.util.TimerThread.run(Timer.java:506)
2022-02-08 13:58:26 E/EntryLib: 无法创建新表TABLE_24，五秒后重试！（4/5）
2022-02-08 13:58:26 W/stderr: org.sqlite.SQLiteException: [SQLITE_ERROR] SQL error or missing database (table TABLE_23 already exists)
2022-02-08 13:58:26 W/stderr:   at org.sqlite.core.DB.newSQLException(DB.java:1012)
2022-02-08 13:58:26 W/stderr:   at org.sqlite.core.DB.newSQLException(DB.java:1024)
2022-02-08 13:58:26 W/stderr:   at org.sqlite.core.DB.throwex(DB.java:989)
2022-02-08 13:58:26 W/stderr:   at org.sqlite.core.NativeDB._exec_utf8(Native Method)
2022-02-08 13:58:26 W/stderr:   at org.sqlite.core.NativeDB._exec(NativeDB.java:94)
2022-02-08 13:58:26 W/stderr:   at org.sqlite.jdbc3.JDBC3Statement.executeUpdate(JDBC3Statement.java:102)
2022-02-08 13:58:26 W/stderr:   at com.billyang.entrylib.Database.DatabaseAutoArranger.rearrange(DatabaseAutoArranger.java:293)
2022-02-08 13:58:26 W/stderr:   at com.billyang.entrylib.Database.DatabaseAutoArranger.run(DatabaseAutoArranger.java:490)
2022-02-08 13:58:26 W/stderr:   at java.base/java.util.TimerThread.mainLoop(Timer.java:556)
2022-02-08 13:58:26 W/stderr:   at java.base/java.util.TimerThread.run(Timer.java:506)
2022-02-08 13:58:31 E/EntryLib: 无法创建新表TABLE_24，五秒后重试！（5/5）
2022-02-08 13:58:31 W/stderr: org.sqlite.SQLiteException: [SQLITE_ERROR] SQL error or missing database (table TABLE_23 already exists)
2022-02-08 13:58:31 W/stderr:   at org.sqlite.core.DB.newSQLException(DB.java:1012)
2022-02-08 13:58:31 W/stderr:   at org.sqlite.core.DB.newSQLException(DB.java:1024)
2022-02-08 13:58:31 W/stderr:   at org.sqlite.core.DB.throwex(DB.java:989)
2022-02-08 13:58:31 W/stderr:   at org.sqlite.core.NativeDB._exec_utf8(Native Method)
2022-02-08 13:58:31 W/stderr:   at org.sqlite.core.NativeDB._exec(NativeDB.java:94)
2022-02-08 13:58:31 W/stderr:   at org.sqlite.jdbc3.JDBC3Statement.executeUpdate(JDBC3Statement.java:102)
2022-02-08 13:58:31 W/stderr:   at com.billyang.entrylib.Database.DatabaseAutoArranger.rearrange(DatabaseAutoArranger.java:293)
2022-02-08 13:58:31 W/stderr:   at com.billyang.entrylib.Database.DatabaseAutoArranger.run(DatabaseAutoArranger.java:490)
2022-02-08 13:58:31 W/stderr:   at java.base/java.util.TimerThread.mainLoop(Timer.java:556)
2022-02-08 13:58:31 W/stderr:   at java.base/java.util.TimerThread.run(Timer.java:506)
2022-02-08 13:58:36 E/EntryLib: 无法完成123456789.db数据库整理工作，即将退出！
```
bot启动时整理数据库，如果__MAIN_TABLE中的序号不连续，就会报上面这个错

**复现步骤 To Reproduce**
复现问题的步骤:
1、数据库中已有序号为1，2，3，4，10，11，12，15，18，22的数据
2、启动bot，此时bot会将数据的序号整理为连续的正整数
3、随后报错TABLE_5已存在
4、重启bot
5、随后报错TABLE_6已存在

**截图 Screenshots**
这个图是出现上面日志后的数据库：![image](https://user-images.githubusercontent.com/21017431/152983151-bd5f3dfa-43fa-40f0-8ae5-c52488464497.png)
这个图是重启后的数据库：
![image](https://user-images.githubusercontent.com/21017431/152983780-8abe1526-8ccd-4704-9207-e55e9f85f499.png)

**环境 Environment**
 - OS: Ubuntu 20.04
 - Mirai Core Version: 2.10.0
 - Mirai Console Version: 2.10.0
 - EntryLib Version: 1.3.1

**Comment by BillYang2016** [comment]
简述一下上述问题，是指“数据库序号在报错过程中一次一次变得连续”吗？

**Comment by BillYang2016** [comment]
经过简易测试，确认问题存在

**Comment by BillYang2016** [comment]
已进行修复，将在1.3.2版本打包并close，如问题仍然存在请reopen本issue

**Comment by BillYang2016** [comment]
已打包
